spring.config.activate.on-profile: local
spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
---

spring.config.activate.on-profile: mysql
spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:13307/demo_batch
      username: root
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver


