spring.application.name: demoBatch

spring.profiles.active: mysql

spring.profiles.include:
  - database

spring:
  batch:
    job:
      name: ${job.name:NONE}

server:
  error:
    whitelabel:
      enabled: false
  shutdown: graceful